### PR TITLE
Allow creation of plugins and add indexed_search

### PR DESCRIPTION
**Pull request by schliesser**
For easy debugging of the indexed search extension I would like to add a page with the plugin. Similar things are done for felogin and form. But the indexed_search isn't a dedicated CType (yet!?). Therefore I've implemented the creation of plugins in general and added the indexed search plugin a the first example.

### CODE REVIEW

**Comment by sbuerk** [comment]
That's not correct. ext:styleguide already contains the ext:indexed_search frontend search plugin.

- let the styleguide frontend demo be generated
- see "styleguide frontend demo" -> "list" in backend

image

image

image

Therefore, this pull-request is not needed.

**Comment by schliesser** [comment]
@sbuerk Thank you! I totally missed that. But wouldn't it be nice to have the plugins available on different pages?

**Comment by sbuerk** [comment]
What plugins ? Styleguide is not there to simulate a full blown page. It showcases things and provide things as base for acceptance tests. So having the search form on one page is enough.

Maybe I do not get your question.

**Comment by schliesser** [comment]
As there are no more other core extensions which are providing a plugin, we just leave it as is. Otherwise we would have the opportunity to have a dedicated page for each plugin.

**Pull request closed without merging**
