### PR TITLE
[TASK] TCA: Add inline mn group example

### PR DESCRIPTION
**Pull request by cjanody**
Hi,
As asked by @tmotyl, here is my sample for inline mn relation using type="group" fields.
Without applying a patch in the core, an warning occurs in file sysext/backend/Classes/Form/Container/InlineControlContainer.php and foreign_unique is ignored.
Thank you,

### CODE REVIEW

**Comment by lolli42** [comment]
Hey. Thanks for your patch! You not only came up with a full TCA structure to show this scenario, but even with a data generator. That's great. I will happily have a look at this specific scenario and your issue. Which core patch or issue are you referring to?

**Comment by cjanody** [comment]
Hi,
Related core issues are https://forge.typo3.org/issues/82104 and https://forge.typo3.org/issues/84735
Each of them has a patch. Mine is less radical because I am not sure that else part is obsolete.
Thanks

**Comment by lolli42** [comment]
Great change!

**Comment by lolli42** [comment]
Merging this right away. Found very minor nitpicks only, I may do them with another patch.

**Pull request merged**
